import Footer from "@/components/Footer";
import { Header } from "@/components/Header";
import { Montserrat } from "next/font/google";
import AppProvider from "@/contexts/AppProvider";
import "@/styles/globals.scss";
import AuthProvider from "@/contexts/AuthProvider";
import { Suspense } from "react";
import Loading from "./loading";

export const metadata = {
  title: "Family Look",
  description: "Generated by Next.js",
};

const montserrat = Montserrat({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <html lang='en' className={montserrat.className}>
      <body suppressHydrationWarning={true}>
        <AppProvider>
          <AuthProvider>
            <Suspense fallback={<Loading />}>
              <Header />
              {children}
              <Footer />
            </Suspense>
          </AuthProvider>
        </AppProvider>
      </body>
    </html>
  );
}
