import Footer from "@/components/Footer";
import { Header } from "@/components/Header";
import { Montserrat } from "next/font/google";
import AppProvider from "@/contexts/AppProvider";
import "@/styles/globals.scss";
import AuthProvider from "@/contexts/AuthProvider";
import { Suspense } from "react";
import Loading from "./loading";
import { usePathname } from "next/navigation";
import { ADMIN_URL } from "@/utils/consts";
import { headers } from "next/headers";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const montserrat = Montserrat({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <html lang='en' className={montserrat.className}>
      <body>
        <AuthProvider>
          <AppProvider>
            <Suspense fallback={<Loading />}>
              <Header />
              {children}
              <Footer />
            </Suspense>
          </AppProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
