import { Montserrat } from "next/font/google";

import "@/styles/globals.scss";

import { ReactNode, Suspense } from "react";
import Loading from "./loading";
import Footer from "components/Footer";
import { Header } from "components/Header";
import AppProvider from "contexts/AppProvider";
import AuthProvider from "contexts/AuthProvider";
import StoreProvider from "contexts/StoreProvider";
import Providers from "contexts/Providers";

export const metadata = {
  title: "Family Look",
  description: "Generated by Next.js",
};

const montserrat = Montserrat({ subsets: ["latin"] });

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang='en' className={montserrat.className}>
      <body suppressHydrationWarning={true}>
        <Providers>
          <Suspense fallback={<Loading />}>
            <Header />
            {children}
            <Footer />
          </Suspense>
        </Providers>
      </body>
    </html>
  );
}
